In [1]:
import numpy as np
import pandas as pd

import scipy
from scipy.cluster.hierarchy import  dendrogram, linkage, fcluster, cophenet
from scipy.spatial.distance import cdist

from pylab import rcParams
import matplotlib.pyplot as plt

import sklearn
from sklearn.cluster import AgglomerativeClustering
import sklearn.metrics as sm

In [2]:
np.set_printoptions(precision=4, suppress=True)
plt.figure(figsize=(10, 3))

<Figure size 720x216 with 0 Axes>

<Figure size 720x216 with 0 Axes>

In [7]:
df = pd.read_csv('movieParsing.dat')
X = np.array(df.drop(['MovieID'], 1).astype(float))
print(X)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [8]:
Z = linkage(X,'ward')

In [ ]:
dendrogram(Z, truncate_mode='lastp', p=12, leaf_rotation)